# DOCUMENTATION: https://docs.artillex-studios.com/axafkzone.html

prefix: "<gradient:#FF8800:#CC0055><b>AxAFKZone</b></gradient> &7Â» "

# 1 - HH:MM:SS, for example 01:25:35
# 2 - short format, for example 20m
# 3 - text format, for example 01h 25m 35s
timer-format: 3

# you must define at least 1
# requires a restart to update
command-aliases:
  - "axafkzone"
  - "afkzone"
  - "axaz"

# should the timer reset after a player gets their afk zone rewards?
# this is just for the placeholders, it will not change functionality
reset-after-reward: false

# how many players can gain rewards at once from a single ip?
# set to -1 for unlimited
zone-per-ip-limit: -1

# should the bossbar progress start from full or empty?
# directions:
# 0 - decreasing value (starts filled)
# 1 - increasing value (starts empty)
bossbar-direction: 0

# do not change this
version: 2